CREATE DATABASE IF NOT EXISTS fortnite_spawn;

use fortnite_spawn;

CREATE TABLE IF NOT EXISTS spawn
(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(500) NOT NULL,
	PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS user
(
	id INT NOT NULL AUTO_INCREMENT,
	login VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
